<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 10.2 - Deployment via Streamlit

### Introduction

**Note**: This notebook should work on your local machine.

The purpose of this lab is to take you through the process of deploying a machine learning web app on a publicly hosted platform (streamlit.io and optionally render.com). A trained model will be created using the Scikit-learn pipeline (combining loading, preprocessing and training steps), then separate files of Python code and text will need to be completed to make deployment possible. Firstly the app will be deployed to your local machine (so that you can view it in your browser). Once that it is successful, the files will be uploaded to a new repository you create in GitHub and then Streamlit or Render will read from this to host the application via a publicly accessible URL.

The app will take in a text string from a user and output a prediction of whether that string is expressing positive or negative sentiment. The model is created using methods from Module 8 (Natural Language Processing). Since the training data used to create the model is small (300 records), the prediction may only be accurate around 70% of the time. In future you may wish to improve this app's performance or develop your own app in a similar manner.

The following files are needed to create the app (they should be in the same folder as this notebook):

- requirements.txt
- app.py
- model.joblib
- utils.py
- .streamlit/ (folder containing config.toml)


Firstly we will see how a predictive model can be created as a pipe which combines the preprocessing, feature engineering and model training steps. This model is then saved as a joblib pickle file which can be reloaded at any time to avoid retraining.

This trained model can be loaded within your production environment along with required packages and real-time predictions can be made by calling its predict() method.

Streamlit enables apps to be deployed rapidly with minimal knowledge of HTML or CSS. Some of the key concepts are described at https://docs.streamlit.io/get-started/fundamentals/main-concepts. Sample apps can be seen at https://streamlit.io/gallery.

### Model Training and Testing

In [2]:
!pip install numpy==1.26.4


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 281.8 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 327.7 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 271.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 3.2 MB/s eta 0:00:05
    --------------------------------------- 0.2/15.8 MB 3.4 MB/s eta 0:00:05
    --------------------------------------- 0.4/15.8 MB 3.2 MB/s eta 0:00:05
   - -------------------------------------- 0.5/15.8 MB 3.2 MB/s eta 0:00:05
   - -------------------------------------- 0.6/15.8 MB 3.0 MB/s eta 0:00:06
   --- ------------------------------------ 1.4/15.8 MB 5.6 MB/s eta 0:00:03
   

  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.


In [8]:
!python -m spacy download en_core_web_sm

     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------------------------------------- 0.0/12.8 MB 165.2 kB/s eta 0:01:18
     --------------------------------------- 0.1/12.8 MB 409.6 kB/s eta 0:00:32
      --------------------------------------- 0.2/12.8 MB 1.3 MB/s eta 0:00:11
     - -------------------------------------- 0.6/12.8 MB 2.5 MB/s eta 0:00:05
     --- ------------------------------------ 1.0/12.8 MB 3.8 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/12.8 MB 5.3 MB/s eta 0:00:03
     ------ --------------------------------- 2.2/12.8 MB 6.2 MB/s eta 0:00:02
     -------- ------------------------------- 2.8/12.8 MB 6.6 MB/s eta 0:00:02
     --------- ------------------------------ 3.0/12.8 MB 7.0 MB/s eta 0:00:02
     ----------- ---------------------------- 3.8/12.8 MB 7.5 MB/s eta 0:00:02
     ------------- -------------------------- 4.3/12.8 MB 7.7 MB

In [1]:
## Import Libraries
import numpy as np
import pandas as pd
import regex as re
import spacy
import streamlit as st

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.base import BaseEstimator, TransformerMixin
import joblib

The training data set is `sentiments.csv`, a dataset used in the NLP module.

In [2]:
# Read in the data
df = pd.read_csv('sentiments.csv')

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.head()

text  sentiment source
0                           Wow... Loved this place.          1   yelp
1                                 Crust is not good.          0   yelp
2          Not tasty and the texture was just nasty.          0   yelp
3  Stopped by during the late May bank holiday of...          1   yelp
4  The selection on the menu was great and so wer...          1   yelp

Next we define a function to do some preprocessing.

In [5]:
def clean_text(text):
    # reduce multiple spaces and newlines to only one
    text = re.sub(r'(\s\s+|\n\n+)', r'\1', text)
    # remove double quotes
    text = re.sub(r'"', '', text)

    return text

In [6]:
df['text'] = df['text'].apply(clean_text)

The following NLP model is used for further preprocessing. The following steps are the same as used in Module 8.

In [9]:
import en_core_web_sm
nlp = en_core_web_sm.load()

In [10]:
def convert_text(text):
    sent = nlp(text)
    ents = {x.text: x for x in sent.ents}
    tokens = []
    for w in sent:
        if w.is_stop or w.is_punct:
            continue
        if w.text in ents:
            tokens.append(w.text)
        else:
            tokens.append(w.lemma_.lower())
    text = ' '.join(tokens)

    return text

In [11]:
df['short'] = df['text'].apply(convert_text)

In [12]:
# Features and Labels
X = df['short']
y = df['sentiment']

In [13]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [14]:
classifier = LinearSVC()

In [15]:
# create a matrix of word counts from the text
# use TF-IDF
tfidf = TfidfVectorizer()
# do the actual counting
A = tfidf.fit_transform(X_train, y_train)

# train the classifier with the training data
classifier.fit(A.toarray(), y_train)

# do the transformation for the test data
# NOTE: use `transform()` instead of `fit_transform()`
B = tfidf.transform(X_test)

# make predictions based on the test data
predictions = classifier.predict(B)

# check the accuracy
print('Accuracy: %.4f' % accuracy_score(y_test, predictions))

Accuracy: 0.7767


We will not attempt to improve on the performance in this lab as we are more interested in how to deploy the model.

Next we create a pipeline to simplify the process of model creation. We first define a preprocessor class which applies the `clean_text` and `convert_text` functions defined earlier.

In [16]:
class preprocessor(TransformerMixin, BaseEstimator):

    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
         return X.apply(clean_text).apply(convert_text)

Next we combine the preprocessing, feature engineering and modelling steps into a single pipe.

In [17]:
pipe = make_pipeline(preprocessor(), tfidf, classifier)
pipe.fit(df['text'],df['sentiment'])

Pipeline(steps=[('preprocessor', preprocessor()),
                ('tfidfvectorizer', TfidfVectorizer()),
                ('linearsvc', LinearSVC())])

**Exercise**: test the resulting model on phrases of positive and negative sentiment.

In [18]:
pipe.predict(pd.Series('bad'))

array([0], dtype=int64)

In [19]:
pipe.predict(pd.Series('good'))

array([1], dtype=int64)

In [20]:
pipe.predict(pd.Series('goblin'))

array([0], dtype=int64)

Once satisfied that we have a model ready for deployment, we can write a self-contained script that creates the model and saves it as a joblib file. By doing so from a script rather than the notebook we simplify the process when deploying.

**Exercise**:
1. Review the code in model.py.
2. Open an Anaconda prompt (Windows) or Terminal window (Mac).
3. Navigate to the folder where model.py is located using the command `cd "<path to your folder>"`.
4. At the prompt enter `python model.py`. After a few moments this creates a file `model.joblib`.

Let us load this model and verify that it alone can be used to make predictions.

In [21]:
newpipe = joblib.load(open('model.joblib','rb'))

In [22]:
type(newpipe)

sklearn.pipeline.Pipeline

Testing this out:

In [23]:
print(newpipe.predict(pd.Series('awesome place'))[0])
print(newpipe.predict(pd.Series('terrible!'))[0])
print(newpipe.predict(pd.Series('very interesting'))[0])

1
0
1


We can then write a self-contained script that loads the model and can make predictions on the fly. This is partially done for you in the file "app.py".

**Exercise**: Refer to app.py and fill in the missing code based on the code above using a text editor such as Spyder or even Jupyter. Observe how it links to utils.py which contains the preprocessing functions.

### Local hosting

Using Anaconda prompt (Windows) or a Terminal window (Mac) run "streamlit run app.py". This deploys the app locally on http://localhost:8501/ (or similar) which you can then view on the browser. The file app.py may require debugging before it runs successfully.

**Bonus Exercise**: Redesign the webpage by adding other components. You can use the cheat sheet at https://docs.streamlit.io/library/cheatsheet as a reference.

### Deployment via streamlit.io

So far you have deployed your model on your local machine. Now we seek to deploy it publicly.

streamlit.io is intended to deploy Streamlit apps seamlessly without worrying about infrastructure.

There is one additional file needed for external deployment of your model:
- requirements.txt includes the versions of packages that are to be used with the app.

To update the `requirements.txt` file use the `__version__` attribute to see the version of packages being used. This ensures that your model is reproducible on other computing environments.

In [24]:
joblib.__version__

'1.2.0'

In [25]:
st.__version__

'1.30.0'

Log into your GitHub account (create one if you have not already done so) and create a new repository containing the following files.

- requirements.txt
- app.py
- model.joblib
- utils.py
- .streamlit/ (folder containing config.toml)

This config.toml allows one to set themes such as the type of background to display.

Next sign up for a free account at https://streamlit.io/ and once signed in, go to https://share.streamlit.io/ and click the blue "New app" button. Under "Repository" specify the GitHub repository where your app is located (in the form username/reponame). The default URL is based on the app's location in GitHub, but that may be changed. Under "main file path" enter `app.py` replacing `streamlit-app.py`. Finally click the "Deploy!" button. If successful the app will deployed to the specified url (it may take several minutes). An example can be seen at https://iod-sentiment-app.streamlit.app/.

If there are issues, click on the "Manage app" button at the bottom right to view the app's logs. Files such as requirements.txt can be edited directly within GitHub.

Further details are at https://docs.streamlit.io/streamlit-community-cloud/manage-your-app.

If you managed to see your app successfully, congratulations! You now know how to deploy an app on the cloud. To make it visible to others, go to your app's settings and under "Sharing" -> "Who can view this app" select "This app is public and searchable".

### Deployment via render.com (optional)

Render is a general-purpose cloud platform that goes beyond deploying streamlit apps. It can host a broader range of web applications, APIs, databases and more.

Sign up for a free account at https://dashboard.render.com/register (a Platform As A Service) by connecting via your GitHub account.

Once signed into dashboard.render.com click "New Web Service" under Web Services.

From "connect GitHub account", select the repository containing the above files.

Choose a unique name for the web service and leave the root directory blank. Under "start command" enter `streamlit run app.py`.

Finally click "Create Web Service". It may take a few minutes to work but
upon seeing "Booting worker with pid:" go to the url specified. An example can be seen at https://streamlit-sentiment.onrender.com/


Note that if working in part of a larger software system it is good practice to have versioning of code (e.g. with GitHub) and also make use of CI/CD software.

### References

More information on pipelines:
- https://gist.github.com/amberjrivera/8c5c145516f5a2e894681e16a8095b5c
- https://scikit-learn.org/stable/modules/compose.html#pipeline

Deploying Streamlit apps on Render and Streamlit Cloud:
- https://www.youtube.com/watch?v=bXRVgg2iWyc



---



---



> > > > > > > > > © 2024 Institute of Data


---



---



